# Generated by Django 4.2.13 on 2024-06-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_languages_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
    ]
